### ISSUE TITLE
Bill of material

### ISSUE THREAD

**Issue by svendhaugaard** [makerbase-mks/MKS-TFT-Hardware#1]
Dear Makerbase team,

Thank you for publishing your software source code and hardware design. Would it be possible that you also share the bill of material? This would be a great help to understand the hardware design.

Thanks and best regards
Svend

**Comment by makerbase-mks** [comment]
Hi! I has upload TFT35's BOM, you can refter to it.

**Comment by svendhaugaard** [comment]
Thank you

**Comment by svendhaugaard** [comment]
Sorry to ask again but what type is the TFT? BOMonly says TFT35
