### ISSUE TITLE
What development environment to use with the MKSTFT28 project source code?

### ISSUE THREAD

**Issue by digant73** [makerbase-mks/MKS-TFT-Hardware#3]
I downloaded the source code for my MKSTFT28 and I would like to costomize/add some menus and features but it seems no development environment project file is provided with the source code.
Is there any possibility to provide for example a PlatformIO project for Visual Studio Code or any other well known development environment?

**Comment by makerbase-mks** [comment]
The original one is based on IAR and will be migrated later
