### ISSUE TITLE
[FR] TFT screens information request

### ISSUE THREAD

**Issue by DanJunior78** [makerbase-mks/MKS-TFT-Hardware#5]
Hello,
I've a few boards from MKS and various LCD and TFT screens.
What I'm missing on all TFTs,if it's the TFT35 or the TS35, there is no similar handling and possibility like on a LCD 12864. Without it's really hard to handle the printer directly. The main screen is not available with information like on the LCD.
Is there something planned at MKS to do something similar to Bigtreetech with their dual screen modes or to improve the TFT software to handle all the things like the LCD does?
Sorry, it's not a bug report,more a feature request.
Regards
(I've a Bigtreetech dual TFT screen and I really don't like to miss this feature)

**Comment by mks-viva** [comment]
Hi! Thank you for your feedback, the current MKS TFT hardware can hardly support the functions you mentioned. But we have adopted another method, MKS Robin Nano V2+MKS TS35, which can also display multiple interfaces

**Comment by DanJunior78** [comment]
Thanks for your feedback.
